fix(docker): switch to cmake
The makefile is currently not linking the
sdl library correctly leading to following
linker error:

    main.c:(.text.startup+0xc): undefined reference to `sdl_init'
    main.c:(.text.startup+0x58): undefined reference to `sdl_display_flush'
    main.c:(.text.startup+0xbd): undefined reference to `sdl_mouse_read'
    main.c:(.text.startup+0xf0): undefined reference to `sdl_keyboard_read'
    main.c:(.text.startup+0x12b): undefined reference to `sdl_mousewheel_read'

Switching to builing with cmake fixes the error.